models.py
from datetime import datetime
from time import time
import re

from flask_security import UserMixin, RoleMixin
from app import db


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


posts_tags = db.Table('posts_tags',
                      db.Column('post_id', db.Integer,
                                db.ForeignKey('post.id')),
                      db.Column('tag_id', db.Integer,
                                db.ForeignKey('tag.id'))
                      )


roles_users = db.Table('roles_users',
                       db.Column('user_id', db.Integer,
                                 db.ForeignKey('user.id')),
                       db.Column('role_id', db.Integer,
                                 db.ForeignKey('role.id'))
                       )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    slug = db.Column(db.String(150), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    tags = db.relationship('Tag', secondary=posts_tags,
                           backref=db.backref('posts'), lazy='dynamic')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = str(int(time()))

    def __repr__(self):
        return f'<Post id: {self.id}, title:{self.title}>'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    slug = db.Column(db.String(150), unique=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.slug = self.generate_slug()
    
    def generate_slug(self):
            if self.title:
                self.slug = slugify(self.title) 
            else:
                self.slug = str(int(time()))

    def __repr__(self):
        return f'<Tag id: {self.id}, title:{self.title}>'


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean)
    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('useres', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), unique=True)

posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask, redirect, url_for, request
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_sqlalchemy import SQLAlchemy
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_admin import AdminIndexView
from flask_security import Security, current_user, SQLAlchemyUserDatastore
from config import Config
import os
 
app = Flask(__name__)

mode = os.environ.get("MODE")
if mode == "PRODUCTION":
    app.config.from_object("config.ProductionConfig")
elif mode == "TESTING":
    app.config.from_object("config.TestingConfig")
else:
    app.config.from_object("config.DevelopmentConfig")

db = SQLAlchemy(app)

from models import *

migrate = Migrate(app, db)
manager = Manager(app)

manager.add_command('db', MigrateCommand)

class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self,name, **kwargs):
        return redirect(url_for('security.login', next=request.url))

class AdminView(AdminMixin, ModelView):
    pass

class HomeAdminView(AdminMixin, AdminIndexView):
    pass

class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        if is_created:
            model.generate_slug()
        return super().on_model_change(form, model, is_created)   

class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body', 'tags']

class TagAdminView(AdminMixin, BaseModelView):
    pass

admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))

admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

# Flask-security

user_datastore  = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
from app import db
import views
from posts.blueprint import posts


app.register_blueprint(posts, url_prefix='/blog')
# localhost:5000/blog/

if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import request

from flask import redirect
from flask import url_for
from flask_security import login_required
from models import *
from .forms import PostForm
from app import db

posts = Blueprint('posts', __name__,
                  template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def post_create():
    form = PostForm()

    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Something went wrong :(')
        return redirect(url_for('posts.post_detail', slug=post.slug))

    return render_template('posts/post_create.html', form=form)

# localhost:5000/blog/


@posts.route('/')
def posts_list():
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) |
                                  Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())

    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    pages = posts.paginate(page=page, per_page=1)
    return render_template('posts/posts.html', posts=posts, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    return render_template('posts/post_detail.html', post=post)


@posts.route('/tags/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    return render_template('posts/tag_detail.html', tag=tag)


@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def post_update(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit.html', post=post, form=form)

views.py
from flask import render_template
from app import app


@app.route('/')
def index():
    return render_template('index.html')


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block title %}
Edit post
{% endblock%}


{% block content %}
<h1>Edit "{{ post.title }}"</h1>
<form action="{{ url_for('posts.post_update', slug=post.slug )}}" method="POST">

    {% for field in form %}
    <div class="form-group">
        {{ field.label() }}
        {{ field(class="form-control") }}
    </div>
    {% endfor %}
    <button class="btn btn-primary">Submit</button>


</form>
{% endblock %}

posts/templates/posts/includes/card.html
<div class="card mb-4 mt-4">
    <h5 class="card-header">{{ post.created.date() }}</h5>
    <div class="card-body">
        <h5 class="card-title"> <a href="{{ url_for('posts.post_detail', slug=post.slug)}}"> {{ post.title }}</a></h5>
        <p class="card-text">{{ post.body }}</p>
        <a href="{{ url_for('posts.post_detail', slug=post.slug)}}" class="btn btn-light">Read more...</a>
    </div>
    {% if post.tags.count() %}
    <div class="card-footer text-muted">
        {% for tag in post.tags %}
        <a href="{{url_for('posts.tag_detail', slug=tag.slug)}}"><span
                class="badge bg-primary">{{ tag.title }}</span></a>
        {% endfor%}
    </div>
    {% endif %}
</div>

posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block title %}
Create new post
{% endblock%}


{% block content %}
<h1>Create new post</h1>
<form action="{{ url_for('posts.post_create') }}" method="POST">

    {% for field in form %}
    <div class="form-group">
        {{ field.label() }}
        {{ field(class="form-control") }}
    </div>
    {% endfor %}
    <button class="btn btn-primary">Submit</button>


</form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock%}


{% block content %}
<h1>{{ post.title }}</h1>
<div class="">
    {{ post.body }}
</div>

{% endblock%}

posts/templates/posts/posts.html
{% extends 'base.html' %}

{% block title %}
Posts list
{% endblock%}

{% block content %}
<h1>Posts</h1>
{% for post in pages.items %}
{% include 'posts/includes/card.html' %}
{% endfor %}

<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item {% if not pages.has_prev %} disabled {% endif %}">
            <a class="page-link" href="./?page={{pages.prev_num}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>

        {% for page in pages.iter_pages() %}

        <li class="page-item {% if page == pages.page %} active {% endif%}"><a class="page-link"
                href="./?page={{ page }}">{{ page }} </a></li>

        {% endfor %}

        <li class="page-item {% if not pages.has_next %} disabled {% endif %}">
            <a class="page-link" href="./?page={{pages.next_num}}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
{% endblock%}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
Posts with "{{ tag.title }}" tag
{% endblock%}


{% block content %}
<h1>Posts with "{{ tag.title }}" tag </h1>
{% for post in tag.posts%}
{% include 'posts/includes/card.html' %}
{% endfor %}
{% endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">    
    <link rel="stylesheet" href="/static/css/styles.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <title>
        {% block title %}

        {% endblock%}
    </title>
</head>

<body>
    <nav class="navbar navbar-expand-sm  navbar-dark bg-dark mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('index')}}">MyBlog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#collapsibleNavbar" >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('posts.posts_list')}}">Blog</a>
                    </li>
                    {% if current_user.has_role('admin') %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Edit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('security.logout')}}">Log out</a>
                    </li>
                    {% endif%}    
                </ul>
                <form class="d-flex" method="GET">
                    <input class="form-control me-2" type="search" placeholder="Search" name="q">
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                {% block content %}

                {% endblock%}
            </div>
        </div>
    </div>

</body>

</html>

templates/index.html
{% extends 'base.html'%}

{% block title %}
Index page
{% endblock%}

{% block content %}
<h1>Index page</h1> 


<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempus luctus felis, sit amet consequat nunc maximus ut. Donec tempor sollicitudin elementum. Praesent in nunc lacinia, vulputate quam ut, accumsan ex. Cras pulvinar ante orci, consequat commodo lectus rutrum id. Fusce urna arcu, vehicula ut dui et, convallis ultrices velit. Phasellus diam massa, laoreet sed mollis quis, convallis nec tellus. Proin quis euismod sem. Sed vehicula condimentum mauris, sed congue lorem facilisis et. Phasellus eu mauris fringilla, rutrum mi eget, tempor nunc. Aenean gravida, ante sed imperdiet bibendum, enim ante rutrum mauris, a tincidunt tortor diam ac quam. Quisque vestibulum risus eget dui lacinia scelerisque. Quisque lacinia, nibh id lacinia finibus, odio velit sagittis nulla, ac dictum sem nisl et lorem. Quisque malesuada a diam quis aliquet. Phasellus rhoncus nec quam sed blandit. Ut placerat ultrices quam et elementum. Etiam sit amet luctus ligula, id elementum diam.

Suspendisse ut tincidunt sem. Integer sodales sagittis diam, ut lacinia libero commodo et. In hac habitasse platea dictumst. Sed dignissim lorem in mattis interdum. Donec mollis nibh vitae enim dignissim, non pulvinar turpis tincidunt. Morbi elit magna, pellentesque nec magna id, pellentesque porttitor lectus. Maecenas semper, leo at molestie tempus, nunc velit imperdiet arcu, sit amet cursus urna ipsum sed magna. Vivamus commodo pharetra vehicula.

Suspendisse et velit augue. Ut sed ex maximus, feugiat tellus nec, fringilla libero. Interdum et malesuada fames ac ante ipsum primis in faucibus. In a ex in leo pharetra tristique a sit amet neque. Etiam venenatis fermentum lacus, eu sagittis dolor rhoncus et. Nulla egestas mi id sem laoreet varius. Integer vel nunc viverra, pharetra tellus sed, rhoncus odio. Proin sit amet consectetur metus. Proin lacinia gravida metus, fermentum semper ante bibendum ac. Etiam rutrum libero ligula, id condimentum quam lacinia ut.

Fusce rutrum rutrum efficitur. Vestibulum euismod risus sed faucibus dignissim. Quisque aliquet quis nisl vitae ullamcorper. Phasellus semper consectetur sodales. Aliquam maximus fermentum sapien eu blandit. Duis ullamcorper ultricies ante. Mauris tempus tempus felis non consectetur.

Integer suscipit mattis magna, in posuere urna posuere in. Mauris egestas tellus sed massa ornare viverra. In sagittis faucibus risus vel vestibulum. Nulla porttitor ante varius, pharetra nisi sed, pharetra felis. Proin condimentum lectus sem, ac finibus est laoreet non. Integer ac pulvinar lorem, suscipit blandit risus. Maecenas velit odio, laoreet eu tempus in, auctor non neque. Quisque id ipsum vitae nulla dictum gravida vel ac dolor.
</p>
{% endblock%}s

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base.html' %}

{%  block content %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Login') }}</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email, class='form-control') }}
  {{ render_field_with_errors(login_user_form.password, class='form-control') }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit, class='btn btn-success') }}
</form>
{% include "security/_menu.html" %}

{% endblock %}